spring:
  application:
    name: ewm-stats-service
  sql:
    init:
      mode: always
  datasource:
    username: stats
    schema: classpath:schema.sql
    url: jdbc:postgresql://stats-db:5432/stats
    driverClassName: org.postgresql.Driver
    password: stats
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none

server:
  port: 9090

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG