spring:
  application:
    name: ewm-main-service
  sql:
    init:
      mode: always
  datasource:
    username: main
    schema: classpath:schema.sql
    url: jdbc:postgresql://ewm-db:5432/main
    driverClassName: org.postgresql.Driver
    password: main
  jpa:
    properties:
      hibernate:
        format_sql:
    hibernate:
      ddl-auto: none

server:
  port: 8080

client:
  url: http://stats-server:9090